### ISSUE TITLE
Extended Task Features

### ISSUE THREAD

**Issue by jebaum** [itchyny/calendar.vim#50]
Assuming they aren't already implemented and I somehow just missed it, could a couple of features be added for tasks? Namely being able to set due dates, add notes for tasks, and perhaps even reorder tasks within a list although (imo) that's the least essential.

All of these operations seem to be supported by the google tasks api, so it should be possible:
https://developers.google.com/google-apps/tasks/v1/reference/tasks/update
https://developers.google.com/google-apps/tasks/v1/reference/tasks#resource

I'd take a crack at implementing this myself if you're ok with the idea.

**Comment by petobens** [comment]
@itchyny I'm sorry to bother you again. First of all let me say that this is a great plugin that I use on a daily basis. One thing that I would really like to achieve is what I mentioned as the second point in my previous comment:

>ii) I tried to implement it in my vimrc like this au BufWinEnter * if &ft ==# 'calendar' | normal T | endif but it didn't work.

Although I understand this is a Calendar app I would really like to have the Tasklist open once the app starts. Since you know way more vimscript than I do, can you suggest a way of doing this? (i.e something I can put in my vimrc)

**Comment by itchyny** [comment]
Either one of the following settings might the solution.
```vim
autocmd FileType calendar call feedkeys("\<Plug>(calendar_task)")
```
```vim
autocmd FileType calendar call feedkeys("\<Plug>(calendar_task)\<Plug>(calendar_tab)")
```
Or in short,
```vim
autocmd FileType calendar call feedkeys("T")
```
```vim
autocmd FileType calendar call feedkeys("T\<Tab>")
```
However, these ways are not intuitive and the screen is redrawn multiple times.
I'd like to add an option/flag to start the app with the tasklist open.

**Comment by petobens** [comment]
@itchyny  thank you!! 

    autocmd FileType calendar call feedkeys("\<Plug>(calendar_task)")

is exactly what I need (at least until you decide to add or not the flag).
Thanks again for developing this app!

**Comment by itchyny** [comment]
Now you can enable the visibility of the task list on startup by
```vim
let g:calendar_task = 1
```

**Comment by petobens** [comment]
@itchyny  great! thank you!!!
