### ISSUE TITLE
Option to show week numbers

### ISSUE THREAD

**Issue by lervag** [itchyny/calendar.vim#53]
I propose that you add an option to show week numbers in the calendar.

**Comment by mMontu** [comment]
I noticed that the week numbers doesn't show with '-view=year', is this the expected behavior?

**Comment by itchyny** [comment]
Seems that I did not implement because it'd be more difficult to implement in the year view and was less motivated since I've never seen any calendars showing week numbers. But looks inconsistent, I'll implement when I have time to.

**Comment by mMontu** [comment]
OK, thanks for the explanation. I've find them very useful some years ago, though currently I don't use. I noticed they had disappeared on the new version and thought this was an error caused by interaction with some other plugin.
So I'm fine with the current form, and I have to say that its appearance improved a great deal. Nice work!

**Comment by itchyny** [comment]
Thank you for your comment. I actually get glad to see _Nice work!_ comment in the issues because most people install and just _thinks_ that the plugin is good/bad. One thing to point out is that there are two calendar plugins for Vim; the calendar plugin you used years ago was written by mattn and the plugin in this repository is a totally rewritten version by me. So week numbers did not implemented in the new plugin by me, not _disappeared_.

**Comment by lervag** [comment]
Just wanted to add that I also really like this plugin! You've done a great job, @itchyny! :)

**Comment by itchyny** [comment]
Thank you @lervag!

**Comment by mMontu** [comment]
It works like a charm!

I really thought this was a new version of plugin_id=52. Now I see that the whole history is on `:help calendar-introduction`.

I've searched the vim.org and didn't find a reference to this plugin. I think it could be a good idea to insert it there, as many people use that page when searching for plugins.

Once again, thank you very much  :)

**Comment by itchyny** [comment]
My pleasure.

I want to create a tag and upload this plugin to vim.org after closing all the feature requests.
