### ISSUE TITLE
"Other calendars" won't refresh

### ISSUE THREAD

**Issue by martonbalazs** [itchyny/calendar.vim#71]
Hi, thanks for the fantastic app! In my Google calendar I have a few "other calendars" added. After a cleanup of the vim calendar cache they all download properly. However, later on only my own calendar's entries refresh, items on "other calendars" never seem to get updated. Removing the timestamps doesn't help, I have to clean the whole cache and re-authorise to get "other calendars" refreshed. Can you help this somehow? Thanks.

**Comment by itchyny** [comment]
That's what I did not assumed. The only "other calendar" I subscribe is the holiday calendar and the calendar does not update once I download. That's why I dropped them from the calendar list which is updated on the calendar startup. For performance efficiency.
However, if there are some calendars which are updated frequently, I should fix the behaviour. Hmm, probably I'll check if the calendar if it is a holiday calendar or not.

**Comment by martonbalazs** [comment]
The thing is that I have a work calendar and a home calendar. At work home is an "other calendar", at home work is "another calendar". Both change frequently, and it's nice to see them at one place.

Thanks a lot!

**Comment by itchyny** [comment]
Let me confirm; your account does not have permission to write/change events in that home calendar at work, right?

**Comment by martonbalazs** [comment]
Exactly as you write, confirmed. Thanks.

**Comment by martonbalazs** [comment]
This is amazing, thanks so much!!

**Comment by itchyny** [comment]
My pleasure.
