### ISSUE TITLE
Refresh task at startup

### ISSUE THREAD

**Issue by petobens** [itchyny/calendar.vim#82]
Hi @itchyny ,
I love your plugin more every day. I have however one minor problem: if I add a new task and a new event through the web  and then open the calendar app with `:Calendar -task` the new task is not shown in the tasklist. I need to open and close the Calendar app for it to refresh (on the other hand the new event is automatically shown).
Can you reproduce this behaviour?
Thanks in advance

**Comment by itchyny** [comment]
As I have explained in #81, the app does refresh the calendar events three hours after the last update, and the task list as well. Otherwise the app would causes too much download events and results into the performance down. If you switch to the app, why don't you insert your new task with this app?

**Comment by petobens** [comment]
@itchyny  I understood what you explained in #81. What I mean is that if for instance I create a new task with my mobile phone and after three hours I open the vim app with `:Calendar -task` the new task does not show up. I need to close the app and re open it for it to appear.  This doesn't happen with a regular calendar event (i.e if I create a new event with my mobile phone and after three hours I open the vim app then the event shows up).

**Comment by petobens** [comment]
Thank you!
