### ISSUE TITLE
taskwarrior/taskwiki support

### ISSUE THREAD

**Issue by linuxcaffe** [itchyny/calendar.vim#85]
Hi! I've been a taskwarrior.org user for several years. It's a "command-line todo-list manager" and juggles dated tasks nicely, but it has never had the benefit of a true calendar.

Recently, one of the tw dev-team wrote taskwiki (https://github.com/tbabej/taskwiki) which enhances vimwiki with taskwarrior tasks. I've filed a taskwiki issue (https://github.com/tbabej/taskwiki/issues/53) hoping to see taskwiki support your (brilliant) calendar, but the (also brilliant) taskwiki author (tbabej) would need quite a few more clues in order to make this happen. 

This goal (taskwarrior dated tasks in calendar, undated tasks viewable in the Todo list) could be achieved in more that one way:
a) taskwiki integrates/ supports calendar.vim (tbabej needs clues)
b) calendar.vim supports taskwarrior directly (itchyny needs to lean a lot more about taskwarrior)

I'm not a programmer, just an enthusiastic user, but I believe this integration would be "life-changing" so I would be happy to act as a "go-between" if necessary. 

Specific question will be added as comments to this issue, thanks a TON!

**Comment by linuxcaffe** [comment]
1) When I first ran calendar.vim, a prompt asked for the name of a calendar, where would I find that file?

1.a) is the calendar kept in a known format?

**Comment by itchyny** [comment]
I'm not interested in integration with taskwarrior because I('ve) never use it in my workflow. The downloaded items are kept in `~/.cache/calendar.vim/`. The app `calendar.vim` just saves the response of Google Calendar API, thus the format is just as you see in its reference https://developers.google.com/google-apps/calendar/v3/reference/events. I'm very sorry but I close this issue with the wontfix tag because I'll never implement at this moment. If dozens of people requested me to implement, I would register to taskwarrior and check for its API.
