### ISSUE TITLE
How to use input file

### ISSUE THREAD

**Issue by blakesweeney** [itchyny/calendar.vim#96]
I understand the format but where do we put the files? Is there a variable to control this? Also is it possible to have one or more of those files?

**Comment by itchyny** [comment]
I do not understand what you mean. What is *the format* and *the files*?

**Comment by blakesweeney** [comment]
In `:help calendar-input-format` you describe an input format for calendar files. Where does the file go and can I have more than one of them? I would like to use this file to connect with other tools, like taskwarrior.

**Comment by itchyny** [comment]
Check `:help calendar-options-cache_directory`.

**Comment by blakesweeney** [comment]
I wrote `EVENT: 09-27 An event` in to `~/.cache/calendar.vim/example` and I do not see any event called 'An event in my calendar. Am I doing something wrong?

**Comment by itchyny** [comment]
No, no. Open the calendar with `:Calendar` command and press `i` or `a` to input the event.

**Comment by blakesweeney** [comment]
It would be really useful to be able to input events without having to do it manually or using google calendar. This would make this a really good way to integrate with other tools. For example I use taskwarrior for some tasks and it would be great to display the due dates on this calendar. I'm happy to help code some of this if you are interested.

**Comment by itchyny** [comment]
Sorry but I'm not interested in integrating with other tools. The files are basically stored in the format of the response of Google Calendar https://developers.google.com/google-apps/calendar/v3/reference/. I'm very sorry but I close this issue with the wontfix tag because I'm never going to implement at the moment.
https://github.com/itchyny/calendar.vim/issues/85#issuecomment-90032595

**Comment by blakesweeney** [comment]
Ok, thanks for letting me know.
